ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    HEIGHT: 0.60
    RADIUS: 0.25
    SENSORS: ['DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  DEPTH_SENSOR:
    WIDTH: 320
    HEIGHT: 240
    MAX_DEPTH: 10.0
    MIN_DEPTH: 0.3
    HFOV: 90
    POSITION: [0, 0.69, 0]
TASK: 
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.36
  POSSIBLE_ACTIONS: ["VELOCITY_CONTROL"]
  ACTIONS:
    VELOCITY_CONTROL:
      LIN_VEL_RANGE: [0.0, 0.35]
      STRAFE_VEL_RANGE: [-0.15, 0.15]
      ANG_VEL_RANGE: [-10, 10]
      MIN_ABS_LIN_SPEED: 0.035
      MIN_ABS_STRAFE_SPEED: 0.015
      MIN_ABS_ANG_SPEED: 1.0
      USE_STRAFE: False
      AUTO_STOP: False
      MAX_COLLISIONS: -1
      SUCCESS_DISTANCE: 0.36
  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'SUCCESS', 'SPL']
  SUCCESS: 
    SUCCESS_DISTANCE: 0.36
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.36
DATASET:
  TYPE: PointNav-v1
  SPLIT: coda_hard_p1
  DATA_PATH: /coc/testnvme/jtruong33/data/datasets/coda/{split}/{split}.json.gz
