ENVIRONMENT:
  MAX_EPISODE_STEPS: 150
  CURRICULUM: False
SIMULATOR:
  AGENT_0:
    SENSORS: [ "SPOT_LEFT_DEPTH_SENSOR", "SPOT_RIGHT_DEPTH_SENSOR" ]
    HEIGHT: 0.60
    RADIUS: 0.3
  HABITAT_SIM_V0:
    ALLOW_SLIDING: False
  SPOT_LEFT_GRAY_SENSOR:
    TYPE: "SpotLeftGraySensor"
    WIDTH: 120
    HEIGHT: 212
    HFOV: 58.286  # horizontal field of view in degrees
    ORIENTATION: [ -0.4415683, -0.57648225, 0.270526 ]  # Euler's angles (pitch yaw roll)
    POSITION: [ -0.03740343144695029, 0.5, -0.4164822634134684 ]
  SPOT_RIGHT_GRAY_SENSOR:
    TYPE: "SpotRightGraySensor"
    WIDTH: 120
    HEIGHT: 212
    HFOV: 58.286  # horizontal field of view in degrees
    ORIENTATION: [ -0.4415683, 0.57648225, -0.270526 ]  # Euler's angles
    POSITION: [ 0.03614789234067159, 0.5, -0.4164822634134684 ]
  SPOT_LEFT_DEPTH_SENSOR:
    TYPE: "SpotLeftDepthSensor"
    WIDTH: 120
    HEIGHT: 212
    HFOV: 58.286  # horizontal field of view in degrees
    ORIENTATION: [ -0.4415683, -0.57648225, 0.270526 ]  # Euler's angles (pitch yaw roll)
    POSITION: [ -0.03740343144695029, 0.5, -0.4164822634134684 ]
    MAX_DEPTH: 3.5
    MIN_DEPTH: 0.0
    NORMALIZE_DEPTH: True
  SPOT_RIGHT_DEPTH_SENSOR:
    TYPE: "SpotRightDepthSensor"
    WIDTH: 120
    HEIGHT: 212
    HFOV: 58.286  # horizontal field of view in degrees
    ORIENTATION: [ -0.4415683, 0.57648225, -0.270526 ]  # Euler's angles
    POSITION: [ 0.03614789234067159, 0.5, -0.4164822634134684 ]
    MAX_DEPTH: 3.5
    MIN_DEPTH: 0.0
    NORMALIZE_DEPTH: True
  SPOT_SURFACE_NORMAL_SENSOR:
    TYPE: "SpotSurfaceNormalSensor"
    WIDTH: 256
    HEIGHT: 256
TASK:
  TYPE: Nav-v0
  ROBOT: 'Spot'
  SUCCESS_DISTANCE: 0.425

  SENSORS: ['POINTGOAL_WITH_GPS_COMPASS_SENSOR']
  POINTGOAL_WITH_GPS_COMPASS_SENSOR:
    GOAL_FORMAT: "POLAR"
    DIMENSIONALITY: 2
  GOAL_SENSOR_UUID: pointgoal_with_gps_compass

  POSSIBLE_ACTIONS: ["VELOCITY_CONTROL"]
  ACTIONS:
    VELOCITY_CONTROL:
      TIME_STEP: 1.0
      CTRL_FREQ: 240.0
      MUST_CALL_STOP: False
      MIN_ABS_HOR_SPEED: 0.035
      MIN_ABS_LIN_SPEED: 0.035
      MIN_ABS_ANG_SPEED: 1.0
      LIN_VEL_RANGE: [ -0.5, 0.5 ]  # meters per sec
      ANG_VEL_RANGE: [ -30.0, 30.0 ]  # deg per sec
      HOR_VEL_RANGE: [ -0.5, 0.5 ] # meters per sec
      ROBOT_URDF: /coc/testnvme/jtruong33/data/URDF_demo_assets/spot_hybrid_urdf/habitat_spot_urdf/urdf/spot_hybrid.urdf

  MEASUREMENTS: ['DISTANCE_TO_GOAL', 'EPISODE_DISTANCE', 'SUCCESS', 'SPL', 'COLLISIONS']
  SUCCESS:
    SUCCESS_DISTANCE: 0.425

DATASET:
  TYPE: PointNav-v1
  SPLIT: val
  DATA_PATH: /coc/testnvme/jtruong33/data/datasets/pointnav_hm3d_gibson/pointnav_spot_0.3/{split}/{split}.json.gz